import type { Metadata } from 'next'
import { IBM_Plex_Mono, IBM_Plex_Sans } from 'next/font/google'
import '@/app/css/globals.css'
import { Toaster } from '@/components/ui/sonner'
import { AuthProvider } from '@/context/AuthContext'
import { AppProvider } from '@/lib/store'
import { TooltipProvider } from "@/components/ui/tooltip"
import { QueryProvider } from '@/components/providers/query-provider'

const ibmPlexSans = IBM_Plex_Sans({
	variable: '--font-ibmPlex-sans',
	subsets: ['latin'],
})

const ibmPlexMono = IBM_Plex_Mono({
	variable: '--font-ibmPlex-mono',
	subsets: ['latin'],
	weight: ['100', '400', '700'],
	display: 'swap',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body 
				className={`${ibmPlexSans.variable} ${ibmPlexMono.variable} antialiased`}
				suppressHydrationWarning
			>
				<QueryProvider>
					<AuthProvider>
						<TooltipProvider>
							<AppProvider>{children}</AppProvider>
						</TooltipProvider>
						<Toaster position="bottom-right" richColors closeButton />
					</AuthProvider>
				</QueryProvider>
			</body>
		</html>
	)
}
